sudo: true
language: cpp
compiler: gcc

script:
- sudo apt-get install flex bison binutils-avr
- cd avr/make-avr-gcc
- ./getfiles.gcc.sh
- touch ./ok-build-binutils-2.24
- yes|./buildavr-gcc.sh prefix=~/avr
